version: "3"

vars:
  ANDROID_DIR: android
  RN_ANDROID_DIR: RnAndroidHlsApp/android

tasks:
  lint:js:
    desc: Run JS/TS lint
    cmds:
      - npm run lint

  test:js:
    desc: Run JS/TS unit tests
    cmds:
      - node --test --experimental-strip-types

  lint:kt:
    desc: Run Kotlin lint
    dir: "{{.ANDROID_DIR}}"
    cmds:
      - ./gradlew ktlintCheck

  test:kt:
    desc: Run Kotlin unit tests
    dir: "{{.ANDROID_DIR}}"
    cmds:
      - ./gradlew test

  test:kt:app:
    desc: Run Kotlin unit tests for RN app module
    dir: "{{.RN_ANDROID_DIR}}"
    cmds:
      - ./gradlew test

  audit:deps:
    desc: Run dependency audits (npm)
    cmds:
      - npm audit
      - cd RnAndroidHlsApp && npm audit

  ffmpeg:fetch:
    desc: Download ffmpeg-kit AAR into android/libs (requires FFMPEG_KIT_AAR_URL)
    cmds:
      - ./scripts/fetch_ffmpeg_kit_aar.sh

  ffmpeg:build:rn:
    desc: Build ffmpeg-kit AAR from source for RN app (requires ANDROID_SDK_ROOT/ANDROID_NDK_ROOT)
    cmds:
      - ./scripts/build_ffmpeg_kit_aar.sh

  pipe:
    desc: Run all lint and unit tests (fail fast)
    cmds:
      - task: lint:js
      - task: audit:deps
      - task: test:js
      - task: lint:kt
      - task: test:kt

  pipe:full:
    desc: Run all lint and unit tests including RN app module (fail fast)
    cmds:
      - task: pipe
      - task: test:kt:app
